#ifndef MYCONFIG_H
#define MYDONFIG_H

#undef TAPPING_TERM
#define TAPPING_TERM 200

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 2000


//#undef LEADER_TIMEOUT
//#define LEADER_TIMEOUT 300

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 40

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 3

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 0

#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 0

#undef BACKLIGHT_LEVELS
#define BACKLIGHT_LEVELS 3

#define RGBLIGHT_SLEEP
#undef SLEEP_LED_ENABLE

#endif
