# Having a file like this allows you to override Makefile definitions
# for your own particular keymap

RGBLIGHT_ENABLE	= no
SLEEP_LED_ENABLE = no  # Breathing sleep LED during USB suspend
CONSOLE_ENABLE	= yes        # Console for debug(+400)
COMMAND_ENABLE	= yes        # Commands for debug and configuration


#TAP_DANCE_ENABLE = yes

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif

# run "make avrdude" to flash keyboard
