# Having a file like this allows you to override Makefile definitions
# for your own particular keymap

include myrules.mk
RGBLIGHT_ENABLE := yes

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif

# run "make avrdude" to flash keyboard
